### ISSUE TITLE
IMPROVE THE CURRENT LINE HIGHLIGHTING IN DARK SOLARIZED THEME 

### ISSUE THREAD

**Issue by Devashish-Bawa** [cpeditor/cpeditor.github.io#163] opened 2021-05-13 12:58 UTC
It just whitens out the whole line, which makes it impossible to see the current characters nad also try to add more color schemes.

**Comment by coder3101** [comment] 2021-05-13 14:36
Duplicate of https://github.com/cpeditor/cpeditor/issues/533

**Closed** 2021-05-13 14:36 UTC
